version: "3.8"

services:
  nginx:
    build: docker/nginx
    restart: on-failure
    volumes:
      # this will mount the api folder which contains the code to the docker container
      - ./api:/var/www/api:delegated
      # this will mount the nginx logs so that you can check the logs for errors,
      # without logging into the container
      - ./var/logs/nginx/:/var/log/nginx:delegated
      # this will create the server config to serve the api
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/api.conf:delegated
    ports:
    - "90:80"
    depends_on:
      - api
      - ui
    networks:
      - monitoring

  api:
    build: docker/php
    restart: on-failure
    volumes:
      # this will mount the api folder which contains the code to the docker container
      - ./api:/var/www/api:delegated
      # this will mount the custom `.ini` to the container
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - monitoring
    ports:
      - "9000:9000"

  ui:
    build: ./ui
    restart: on-failure
    # below line starts the project
    command: "npm run start"
    depends_on:
      - api
    networks:
      - monitoring
    volumes:
      # this will mount the ui folder which contains the code to the docker container
      - ./ui:/var/www/ui:delegated
      # this will mount the node_modules folder for faster performance
      - nodemodules:/var/www/ui/node_modules
    ports:
      - "3000:3000"

volumes:
  nodemodules: {}

networks:
  monitoring:
    driver: bridge