vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        assets_upload:
            uri_prefix: /storage/assets
            upload_destination: '%kernel.project_dir%/public/storage/assets'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
